"""Runefoble Events Library - Built on eventsource-py."""

from runefoble_events.events import (
    AbsencePenaltyApplied,
    AbsencePenaltyCleared,
    AbsenteeRecapGenerated,
    AutonomousActionResolved,
    BaseRunefobleEvent,
    BoardGridInitialized,
    BoardMoveEvent,
    CharacterCreated,
    CharacterHealthChanged,
    DiceRolled,
    DiceRollEvent,
    EncounterSpawned,
    PlayerJoinedSession,
    PlayerLeftSession,
    PlayerSpokeEvent,
    SceneAtmosphereSet,
    SessionCreated,
    SessionEnded,
    SessionPenaltyEvent,
    SessionStarted,
    SpectatorSessionConnected,
    SpeechIntentParsed,
    StandInActionDecided,
    TokenMoved,
    TokenPlaced,
    TokenRemoved,
    TurnAdvanced,
    WatcherNarrationEvent,
    WatcherNarrationGenerated,
    register_event,
)

__all__ = [
    "register_event",
    "BaseRunefobleEvent",
    "SessionCreated",
    "SessionStarted",
    "PlayerJoinedSession",
    "PlayerLeftSession",
    "TurnAdvanced",
    "SessionEnded",
    "BoardGridInitialized",
    "TokenPlaced",
    "TokenMoved",
    "TokenRemoved",
    "CharacterCreated",
    "CharacterHealthChanged",
    "AbsencePenaltyApplied",
    "AbsencePenaltyCleared",
    "PlayerSpokeEvent",
    "SpeechIntentParsed",
    "WatcherNarrationGenerated",
    "StandInActionDecided",
    "DiceRolled",
    "AbsenteeRecapGenerated",
    "SceneAtmosphereSet",
    "EncounterSpawned",
    "AutonomousActionResolved",
    "SpectatorSessionConnected",

    # Backward-compatible aliases
    "WatcherNarrationEvent",
    "BoardMoveEvent",
    "DiceRollEvent",
    "SessionPenaltyEvent",
]
