"""Event models for Runefoble reactive gameplay, powered by eventsource-py.

All domain events subclass eventsource.domain.event.DomainEvent and are registered
in the global EventRegistry for serialization, stream persistence, and replay.
"""

from runefoble_events.asset import AssetDeleted, AssetUploaded
from runefoble_events.base import BaseRunefobleEvent, register_event
from runefoble_events.board import (
    BoardGridInitialized,
    BoardMoveEvent,
    FogOfWarRevealed,
    TerrainCellModified,
    TokenHazardTriggered,
    TokenMoved,
    TokenPlaced,
    TokenRemoved,
)
from runefoble_events.character import (
    AbsencePenaltyApplied,
    AbsencePenaltyCleared,
    CharacterCreated,
    CharacterHealthChanged,
    CharacterLeveledUp,
    ConditionApplied,
    ConditionRemoved,
    EquipmentSlotUpdated,
    ItemAddedToInventory,
    ItemRemovedFromInventory,
    SessionPenaltyEvent,
    SpellPrepared,
    SpellSlotExpended,
)
from runefoble_events.session import (
    PlayerJoinedSession,
    PlayerLeftSession,
    SessionCreated,
    SessionEnded,
    SessionStarted,
    SpectatorSessionConnected,
    TurnAdvanced,
)
from runefoble_events.watcher import (
    AbsenteeRecapGenerated,
    AutonomousActionResolved,
    DiceRolled,
    DiceRollEvent,
    EncounterSpawned,
    PlayerSpokeEvent,
    SceneAtmosphereSet,
    SpeechIntentParsed,
    StandInActionDecided,
    VoiceAudioConditioned,
    WatcherNarrationEvent,
    WatcherNarrationGenerated,
)

__all__ = [
    "register_event",
    "BaseRunefobleEvent",
    "SessionCreated",
    "SessionStarted",
    "PlayerJoinedSession",
    "PlayerLeftSession",
    "TurnAdvanced",
    "SessionEnded",
    "SpectatorSessionConnected",
    "BoardGridInitialized",
    "TokenPlaced",
    "TokenMoved",
    "TokenRemoved",
    "FogOfWarRevealed",
    "TerrainCellModified",
    "TokenHazardTriggered",
    "BoardMoveEvent",
    "CharacterCreated",
    "CharacterHealthChanged",
    "AbsencePenaltyApplied",
    "AbsencePenaltyCleared",
    "ItemAddedToInventory",
    "ItemRemovedFromInventory",
    "EquipmentSlotUpdated",
    "ConditionApplied",
    "ConditionRemoved",
    "CharacterLeveledUp",
    "SpellPrepared",
    "SpellSlotExpended",
    "SessionPenaltyEvent",
    "PlayerSpokeEvent",
    "SpeechIntentParsed",
    "WatcherNarrationGenerated",
    "WatcherNarrationEvent",
    "StandInActionDecided",
    "DiceRolled",
    "DiceRollEvent",
    "AbsenteeRecapGenerated",
    "SceneAtmosphereSet",
    "EncounterSpawned",
    "AutonomousActionResolved",
    "VoiceAudioConditioned",
    "AssetUploaded",
    "AssetDeleted",
]
