"""Watcher DM utterances, story recaps, and AI stand-in domain events."""

from runefoble_events.watcher import (
    AbsenteeRecapGenerated,
    AutonomousActionResolved,
    CandidateGhostPreviewEmitted,
    CompoundActionResolved,
    DiceRolled,
    DiceRollEvent,
    DMNarrativeWhispered,
    EncounterSpawned,
    IntentDisambiguationRequested,
    PlayerSpokeEvent,
    SceneAtmosphereSet,
    SpeechIntentParsed,
    StandInActionDecided,
    StandInTurnExecuted,
    WatcherActionApproved,
    WatcherActionModified,
    WatcherActionProposed,
    WatcherActionVetoed,
    WatcherNarrationEvent,
    WatcherNarrationGenerated,
)

__all__ = [
    "AbsenteeRecapGenerated",
    "AutonomousActionResolved",
    "CandidateGhostPreviewEmitted",
    "CompoundActionResolved",
    "DMNarrativeWhispered",
    "DiceRollEvent",
    "DiceRolled",
    "EncounterSpawned",
    "IntentDisambiguationRequested",
    "PlayerSpokeEvent",
    "SceneAtmosphereSet",
    "SpeechIntentParsed",
    "StandInActionDecided",
    "StandInTurnExecuted",
    "WatcherActionApproved",
    "WatcherActionModified",
    "WatcherActionProposed",
    "WatcherActionVetoed",
    "WatcherNarrationEvent",
    "WatcherNarrationGenerated",
]
