"""Watcher and gameplay stream domain events package."""

from runefoble_events.watcher_events.actions import (
    CompoundActionResolved,
    IntentDisambiguationRequested,
    VoiceAudioConditioned,
    WatcherActionApproved,
    WatcherActionModified,
    WatcherActionProposed,
    WatcherActionVetoed,
)
from runefoble_events.watcher_events.combat import (
    AutonomousActionResolved,
    CandidateGhostPreviewEmitted,
    DiceRolled,
    DiceRollEvent,
    EncounterSpawned,
    ReactionOpportunityResolved,
    ReactionPromptTriggered,
    SecretTrapTriggered,
    VocalModulatorPresetChanged,
)
from runefoble_events.watcher_events.factions import (
    FactionAgendaAdvanced,
    FactionAgendaSet,
    FactionCreated,
    GeopoliticalShiftOccurred,
    WorldTickExecuted,
)
from runefoble_events.watcher_events.narrative import (
    AbsenteeRecapGenerated,
    DMNarrativeWhispered,
    PlayerSpokeEvent,
    SceneAtmosphereSet,
    SpeechIntentParsed,
    StandInActionDecided,
    StandInTurnExecuted,
    WatcherNarrationEvent,
    WatcherNarrationGenerated,
)

__all__ = [
    "AbsenteeRecapGenerated",
    "AutonomousActionResolved",
    "CandidateGhostPreviewEmitted",
    "CompoundActionResolved",
    "DMNarrativeWhispered",
    "DiceRollEvent",
    "DiceRolled",
    "EncounterSpawned",
    "FactionAgendaAdvanced",
    "FactionAgendaSet",
    "FactionCreated",
    "GeopoliticalShiftOccurred",
    "IntentDisambiguationRequested",
    "PlayerSpokeEvent",
    "ReactionOpportunityResolved",
    "ReactionPromptTriggered",
    "SceneAtmosphereSet",
    "SecretTrapTriggered",
    "SpeechIntentParsed",
    "StandInActionDecided",
    "StandInTurnExecuted",
    "VocalModulatorPresetChanged",
    "VoiceAudioConditioned",
    "WatcherActionApproved",
    "WatcherActionModified",
    "WatcherActionProposed",
    "WatcherActionVetoed",
    "WatcherNarrationEvent",
    "WatcherNarrationGenerated",
    "WorldTickExecuted",
]
